// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	slack "github.com/slack-go/slack"
)

func AnyPtrToSlackGetUsersInConversationParameters() *slack.GetUsersInConversationParameters {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*slack.GetUsersInConversationParameters))(nil)).Elem()))
	var nullValue *slack.GetUsersInConversationParameters
	return nullValue
}

func EqPtrToSlackGetUsersInConversationParameters(value *slack.GetUsersInConversationParameters) *slack.GetUsersInConversationParameters {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *slack.GetUsersInConversationParameters
	return nullValue
}
