// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	slack "github.com/slack-go/slack"
)

func AnySlackMsgOption() slack.MsgOption {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(slack.MsgOption))(nil)).Elem()))
	var nullValue slack.MsgOption
	return nullValue
}

func EqSlackMsgOption(value slack.MsgOption) slack.MsgOption {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue slack.MsgOption
	return nullValue
}
